### PR TITLE
No unitsync singleplayertab

### LINKED ISSUE #469: disable singleplayer tab when unitsync isn't found / selected
it seems to lead to confusion.

not sure if its better to completely disable the tab or print an error message and/or show edit->preferences->spring.

### PR DESCRIPTION
**Pull request by OursDesCavernes**
Fixes #469 
Removes redundant ReloadModlist() call in battle constructor

TODO:
 * Make empty window size match all empty space as minimap does
 * Add some more text to the window
 * Add a better tooltip

### CODE REVIEW

**Comment by Usaga** [comment]
Thanks!

**Comment by Usaga** [comment]
But why you had to change line brakes in battleroomdataviewmodel?

**Comment by OursDesCavernes** [comment]
Git didn't leave me the choice. I couldn't checkout or commit anything without commiting this.
If you check the files changes, this has no effect.

**Comment by OursDesCavernes** [comment]
I think I'll have to delete my fork as fast forward doesn't work anymore because of this.

**Pull request merged**
