### PR TITLE
Some quick improvements

### PR DESCRIPTION
**Pull request by specing**
The promote button was only tested in an autohost. I'm not familiar with the source and cannot assure that these pointers will be valid:
m_battle->m_autohost_manager->GetAutohostHandler().Promote();

### CODE REVIEW

**Comment by specing** [comment]
last commit closes #778

**Comment by abma** [comment]
i'm really against the promote button: there should be an other solution. spamming others imo isn't very effective and just annoying. the other changes look ok, thanks! 

(will revert the button)

**Comment by specing** [comment]
Feel free to hold it up, it was meant for when a better promote system is implement that e.g. makes rooms blink instead of spamming various channels.

**Comment by specing** [comment]
but tbh #main is already a ghost town so spamming it even more does no harm.

**Pull request merged**
