### PR TITLE
Some minimal improvements in GUI

### PR DESCRIPTION
**Pull request by Usaga**
- Improve BattleRoomTab translations
- Limit minimal size of mainwindow
- Add "User left battle" event show in statusbar
- BattleRoomTab: Make combobox for choosing side draws side's icon
- BattleRoomTab: Replace unobvious setup info with icons. May be this way it gets clearer?

### CODE REVIEW

**Comment by abma** [comment]
any objections of getting direct commit access?

**Comment by abma** [comment]
+looks good, thanks!

**Comment by Usaga** [comment]
Now I have problems:
scrsht01

**Comment by Usaga** [comment]
I coused problems for me but now it fixed with https://github.com/springlobby/springlobby/commit/af93a1d792e5c089228e04dc38547a2c4ca6da0b

Giving me direct commit access may be dangerous as I bring bugs in almost every patch I commit))) But I won't be against that))

**Comment by Usaga** [comment]
Giving me direct commit access may be dangerous as I bring bugs in almost every patch I commit))) But I won't be against that)))

**Comment by abma** [comment]
thats the risk when doing changes :)

i introduce a lot of new bugs, too :-|

**Comment by abma** [comment]
ok, renemilk send you an innovation, when accepted you should have direct commit access.

whats your name in lobby? i guess [PO]Usaga? if you have questions i can only suggest to join #springlobby, i'm often online there

**Comment by Usaga** [comment]
Yes, I am [PO]Usaga. Thanks for invite, I will try not to make lobby worse))

**Pull request merged**
