### PR TITLE
Fix weird users sorting behaviour in chat (bug #322)

### PR DESCRIPTION
**Pull request by Usaga**
Now it working fine. But src/lsl changed again...

### CODE REVIEW

**Comment by abma** [comment]
don't use git add -A

maybe you have to run:
git submodule sync
git submodule update

**Comment by abma** [comment]
use git add path/to/filename

or use git gui and select files/changes you want to add to the commit.

**Comment by Usaga** [comment]
I am using git commit -a

**Comment by Usaga** [comment]
Looks like I should not

**Comment by abma** [comment]
can you please revert the submodule change? just for the learning effect ;-)

**Comment by Usaga** [comment]
Done)

**Comment by abma** [comment]
thanks! :)

**Pull request merged**
