### PR TITLE
Improvements in error handling (#303)

### PR DESCRIPTION
**Pull request by Usaga**
- changed logging behaviour: log processed as usual, but errors showed to user
- begin to change inappropriate log priorities (wxLogError where must be wxLogWarning)

### CODE REVIEW

**Comment by Usaga** [comment]
I also made changes in src/lsl/src/lslutils/logging.h but cant commit it because it is in submodule. What should I do?

**Comment by abma** [comment]
fork lsl, create a pull request there...

**Comment by abma** [comment]
sorry, this doesn't work with wxwidgets:
https://github.com/springlobby/springlobby/issues/340

imo errors have to be stored in a threadsafe way and then displayed from main-thread.

**Comment by Usaga** [comment]
Ok. I understand.

**Comment by Usaga** [comment]
Will use boost::thread and mutexes

**Pull request merged**
